<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>09_Promise关键问题</title>
  </head>
  <body>
    <script>
      //01_改变PromiseState的三种方法:resolve/reject/throw
      var p = new Promise((resolve, reject) => {
        resolve("resolved"); // pending => fulfilled/resolved
        // reject("rejected"); // pending => rejected
        // throw "error"; // pending => rejected
      });
      console.log(p);

      // 02_执行多个回调
      p.then((value) => {
        console.log(value + "回调一");
      });
      p.then((value) => {
        console.log(value + "回调二");
      });

      // 03_函数执行先后问题,先改变状态再执行回调
      var p1 = new Promise((resolve, reject) => {
        resolve("ok");
      });
      p1.then(
        (value) => {
          console.log(value + "回调");
        },
        (reason) => {}
      );

      // 04_then方法返回的结果,由then方法中回调函数返回的结果所决定
      var p2 = new Promise((resolve, reject) => {
        // resolve("resolved");
        reject("rejected");
      });
      var result = p2.then(
        (value) => {
          // return "p2ok";
          return new Promise((resolve, reject) => {
            resolve("p2_promise");
          });
        },
        (reason) => {
          return "failed";
        }
      );
      console.log(result);

      // 05_串联多个任务
      var p3 = new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve("resolved");
        }, 1000);
      });
      p3.then((value) => {
        console.log(value);
      })
        .then((value) => {
          console.log(value);
        })
        .then((value) => {
          console.log(value);
        });

      // 06_异常穿透
      var p4 = new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve("resolved");
        }, 1000);
      });
      p4.then((value) => {
        console.log(value);
        throw "error"; // 此处抛出异常
      })
        .then((value) => {
          console.log(value);
        })
        .then((value) => {
          console.log(value);
        })
        .catch((reason) => {
          console.log(reason + " catch");
        });

      // 07_中断Promise链
      var p5 = new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve("resolved");
        }, 1000);
      });
      p5.then((value) => {
        console.log("回调1");
      })
        .then((value) => {
          console.log("回调2");
          return new Promise(() => {}); // 此处return一个pending状态的Promise中断Promise链
        })
        .then((value) => {
          console.log("回调3");
        })
        .catch((reason) => {
          console.log(reason + " catch");
        });
    </script>
  </body>
</html>
